Move @types/request to dependencies (#1059)
soap's d.ts files depend on request. Unfortunately, since request
doesn't ship its own types, that means consumers of soap also need
@types/request. Currently @types/request is just a dev dependency, which
doesn't get installed by `npm install`. The fix is to move
`@types/request` to the dependencies list.

The error looks like this:

```
node_modules/soap/lib/client.d.ts(4,26): error TS7016: Could not find a declaration file for module 'request'. '../../../tests/cases/user/soap/node_modules/request/index.js' implicitly has an 'any' type.
```

Note that this only shows up when consumers compile with --strict, which is
fairly common.  Typescript's user-code tests include soap and detected
it after 0.27 shipped.